spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:DB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org:
      apache:
      http: DEBUG
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
